Assignment1
ashwath462/practice_session pull request #1
Opened 2024-01-11 09:40 UTC by ashwath462

2024-01-17 10:46 UTC, piyushmalviya13 requested changes
Look into the comments

2024-01-17 10:46 UTC, piyushmalviya13 commented on models/ItemFactory.ts
> +                case 'raw':
Use enum here

2024-01-17 10:46 UTC, piyushmalviya13 commented on models/Item.ts
> +    protected type: string;
Make use of the type enum created

2024-01-17 10:46 UTC, piyushmalviya13 commented on utility/utils.ts
> +export function saveItem(item: Item, allItemsList: Item[]): Item[] {
Cover these functions as well in unit tests

2024-01-17 11:14 UTC, ashwath462 commented on index.ts
>  import { add } from './utility/utils';
Done

2024-01-17 11:16 UTC, ashwath462 commented on models/ItemFactory.ts
> +                case 'raw':
Done

2024-01-17 11:17 UTC, ashwath462 commented on models/Item.ts
> +    protected type: string;
Done

2024-01-18 05:37 UTC, piyushmalviya13 approved these changes
Looks good

2024-01-18 05:38 UTC, merged